apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Static-Site
  title: Static Site Publish 
  description: PR para provisionamento de site estatico
  tags:
    - platform
    - terraform
    - aws
    - static-site
  links:
    - title: Documentation
      url: https://backstage.io/docs/features/software-templates
      icon: docs
spec:
  owner: platform_team
  type: infra-as-code
  parameters:
    - title: Dados do projeto
      required:
        - repository
        - project
      properties:
        environment:
          title: Qual ambiente deverá ser provisionado?
          type: string
          description: A qual ambiente se refere?
          default: Production
          enum: [Production, Staging, Development]
        
        project:
          title: A qual projeto se refere? 
          type: string
          description: Informe o nome do projeto ao qual se refere esse provisionamento.
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
          maxLength: 20
        
        repository:
          title: Qual repositório contém o site estático?
          type: string
          description: Nome do repositório.
          
    - title: Qual a squad responsável por esse projeto?
      properties:
        squad:
          title: Squad
          type: string
          description: |
            Selecione a squad responsável por esse projeto.
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - group

  steps:
    - id: template_tf
      name: Captura o template do módulo terraform
      if: ${{ parameters.environment === "Production" }}
      action: fetch:template
      input:
        targetPath: ./templates/outputs/tf
        url: https://github.com/fillipepaz/aws-cloudfront-module/tree/main/static-site/template/terraform
        values:
          project: ${{ parameters.project }}
          distribution_name: ${{ parameters.distribution_name }}
          environment: ${{ parameters.environment }}
          squad: ${{ parameters.squad }}
          repository: ${{ parameters.repository }}
          account: "704151674151"
          org: "fillipepaz"
    
    - id: template_gha
      name: Captura o template do workflow
      if: ${{ parameters.environment === "Production" }}
      action: fetch:template
      input:
        targetPath: ./templates/outputs/gha
        url: https://github.com/fillipepaz/aws-cloudfront-module/tree/main/static-site/template/gha
        values:
          project: ${{ parameters.project }}
          distribution_name: ${{ parameters.distribution_name }}
          environment: ${{ parameters.environment }}
          squad: ${{ parameters.squad }}
          repository: ${{ parameters.repository }}
          account: "704151674151"

    - id: show_workspace
      name: Show workspace files
      action: debug:log
      input:
        listWorkspace: true
  
    - id: terraform_pr
      name: Create terraform PR
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=fillipepaz&repo=infrastructure-versioning
        branchName: 'feat/${{ parameters.project }}/${{ parameters.environment }}/static-site'
        title: 'Criando Site Estático para o projeto ${{ parameters.project }} no ambiente ${{ parameters.environment }}'
        description: |
          ## 'Criando Site Estático para o projeto ${{ parameters.project }} no ambiente ${{ parameters.environment }}'
          [![N|Solid](https://devopsdays.org/events/2024-aracaju/logo.png)]
         
        sourcePath: ./templates/outputs/tf
        targetPath: 'aws/${{ parameters.environment }}/static-site/${{ parameters.project }}'
  
    - id: gha_pr
      name: Create Github Actions PR
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=fillipepaz&repo=${{ parameters.repository }}
        branchName: 'feat/${{ parameters.project }}-deployment'
        title: 'Criando Workflow para o projeto ${{ parameters.project }} no ambiente ${{ parameters.environment }}'
        description: |
          ## 'Criando Workflow do Github Actions para o projeto ${{ parameters.project }} no ambiente ${{ parameters.environment }}'
          [![N|Solid](https://devopsdays.org/events/2024-aracaju/logo.png)]
         
        sourcePath: ./templates/outputs/gha
        targetPath: '.github/workflows'

    - id: label_pr
      name: Add labels to PR
      action: github:issues:label
      input:
        repoUrl: github.com?owner=fillipepaz&repo=infrastructure-versioning
        number: '${{ steps.terraform_pr.output.pullRequestNumber }}'
        labels:
          - IaC
          - Platform Team
          - ${{ parameters.environment }}
          - static-site
    
    - id: label_pr_gha
      name: Add labels to GHA PR
      action: github:issues:label
      input:
        repoUrl: github.com?owner=fillipepaz&repo=${{ parameters.repository }}
        number: '${{ steps.gha_pr.output.pullRequestNumber }}'
        labels:
          - IaC
          - Platform Team
          - ${{ parameters.environment }}
          - static-site

  output:
    links:
      - title: 'Link para o pull request do Terraform'
        url: ${{ steps.terraform_pr .output.remoteUrl }}
        icon: github
      
      - title: 'Link para o pull request do Github Actions'
        url: ${{ steps.gha_pr.output.remoteUrl }}
        icon: github
      
